#!/usr/bin/env node

'use strict';

if (process.argv.length > 2) {
    var command = process.argv[2],
        ProjectJs = require('./project'),
        projectJs = new ProjectJs();

    if (command === "version" || command === "--version" || 
        command === "--v" || command === "-v") {
        console.log(projectJs.getVersion());

    } else if (command === "build") {
        projectJs.buildProject();
    }
}

// var findup = require('findup-sync');
// var path = findup("project.json");
// console.log(process.argv);